- composer.json
- composer.lock
> fix: fix dependency psr/simple-cache

- src/Schema/ForestModel.php
> fix(schema): added support enum for mariaDB

- src/Schema/ForestModel.php
- tests/Unit/ForestModelTest.php
> fix(schema): add support on Mariadb enum

- src/Http/Controllers/AuthController.php
> fix: authentication on production environment

- src/Services/Concerns/HasSearch.php
> fix: searchExtended on model without relations

- src/Facades/JsonApi.php
- src/Http/Controllers/RelationshipsController.php
- src/Http/Controllers/ResourcesController.php
- src/Policies/PermissionPolicy.php
- src/Schema/ForestModel.php
- src/Services/Concerns/ForestCollection.php
- src/Services/Concerns/HasFilters.php
- src/Services/JsonApiResponse.php
- src/Services/SmartFeatures/SmartAction.php
- src/Services/SmartFeatures/SmartField.php
- src/Transformers/BaseTransformer.php
- tests/Feature/Models/Book.php
- tests/Unit/Facades/JsonApiTest.php
- tests/Unit/JsonApiResponseTest.php
- tests/Unit/SmartFieldTest.php
- tests/Unit/Traits/HasFiltersOperatorsTest.php
- tests/Utils/TestTransformer.php
> feat: add deactivate count and refactor smart features

- composer.json
- src/Serializer/JsonApiSerializer.php
> fix(dependency): fix the dependency that serialize api response

- README.md
> fix: readme update documentation link

- config/forest.php
- src/Http/Controllers/ApiMapsController.php
- src/Http/Controllers/AuthController.php
- src/Http/Controllers/RelationshipsController.php
- src/Listeners/RouteMatched.php
- src/Providers/EventProvider.php
- tests/Feature/Listeners/RouteMatchedTest.php
- tests/TestCase.php
> feat(deploy): add FOREST_SEND_APIMAP_AUTOMATIC env to enable automatic sending of the apimap

- src/Http/Middleware/ForestCors.php
- tests/Feature/ForestCorsTest.php
> feat(cors): add access controll allow private network handling 

- src/Schema/Schema.php
- tests/Feature/Listeners/RouteMatchedTest.php
- tests/Feature/SchemaTest.php
- tests/Unit/SchemaTest.php
> fix(schema): fix method that get the driver of the database

- src/Commands/ForestInstall.php
> feat(onboarding): add a url control on forest install command

- routes/routes.php
- src/Commands/ForestInstall.php
- src/Http/Controllers/ApiMapsController.php
- tests/Feature/ApiMapsControllerTest.php
> feat(onboard): allow user to onboard with laravel valet

- routes/routes.php
- src/Http/Controllers/AuthController.php
- tests/Feature/AuthControllerTest.php
> feat(auth): add logout route

- config/forest.php
- src/Facades/ForestSchema.php
- src/Schema/ForestModel.php
- src/Schema/Schema.php
- src/Services/Concerns/ForestCollection.php
- src/Services/ForestSchemaInstrospection.php
- src/Utils/Traits/Schema.php
- tests/Feature/ForestSchemaIntrospectionTest.php
- tests/Feature/Listeners/RouteMatchedTest.php
- tests/Feature/RelationshipsControllerTest.php
- tests/Feature/ResourcesControllerTest.php
- tests/Feature/SchemaTest.php
- tests/TestCase.php
- tests/Unit/SchemaTest.php
- tests/Unit/Traits/SchemaTest.php
- tests/Utils/FakeSchema.php
> feat: add support for multiple models directories

- src/Schema/Concerns/DataTypes.php
> fix: add database type timestamp for schema generation

- composer.lock
> fix(security): update guzzle version (with dependency) to 7.4.5

- src/Auth/Guard/Model/ForestUser.php
- src/Auth/OAuth2/ForestResourceOwner.php
- src/Providers/AuthorizationProvider.php
- tests/Feature/ChartsControllerTest.php
- tests/Feature/IpWhitelistTest.php
- tests/Feature/RelationshipsControllerTest.php
- tests/Feature/ResourcesControllerTest.php
- tests/Feature/ScopesControllerTest.php
- tests/Feature/SmartActionControllerTest.php
- tests/Unit/ForestResourceOwnerTest.php
> fix(charts): user with permissions level that allows charts creation or edition should always be allow to perform charts requests

- src/Auth/AuthManager.php
- src/Auth/OidcClientManager.php
- src/Commands/ForestClear.php
- src/ForestServiceProvider.php
- src/Http/Controllers/AuthController.php
- tests/Feature/AuthControllerTest.php
- tests/Unit/AuthManagerTest.php
- tests/Unit/OidcClientManagerTest.php
> feat(auth): remove callbackUrl parameter on authentication

- src/Services/Concerns/HasIncludes.php
- tests/Unit/Traits/HasIncludesTest.php
> fix(query-builder): patch eagerload relationships on collection

- CHANGELOG.md
- composer.json
- package.json
> chore: merge 1.3.1 into beta

- composer.json
- package.json
> chore: composer beta version

- CHANGELOG.md
> chore: merge main into beta

- src/Commands/ForestInstall.php
> feat(command): add auto publish configuration into forest install command

- composer.json
> fix: add doctrine/dbal dependency to allow use of sqlsrv database

- agentTemplate/forest_admin.php
> chore(config): improve default customisation file

- composer.json
> fix: update minimum version of agent-php packages

- composer.json
> fix(composer): update minimum agent dependencies
